server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microserviceAccountDraft
          uri: lb://microserviceAccountDraft
          predicates:
            - Path=/credit-simulator/**
        - id: microserviceCredit
          uri: lb://microserviceCredit
          predicates:
            - Path=/credit-application/**
        - id: microserviceCustomer
          uri: lb://microserviceCustomer
          predicates:
            - Path=/user-registration/**
        - id: microserviceSavingAccount
          uri: lb://microserviceSavingAccount
          predicates:
            - Path=/tracking-requests/**
        - id: microserviceWorkHistory
          uri: lb://microserviceWorkHistory
          predicates:
            - Path=/credit-evaluation/**